server:
  port: 8090
#  port: 8091
spring:
  application.name: interview
  profiles.active: dev
  redis:
    host: 127.0.0.1
#    host: 172.18.0.3
    port: 6379
#    password: ENC(T7Y99lbcrglxUvKQKS+4mbQdxyIp2k6HcxYvjhComC4zTd/LomKY7VEW6f21RBwO)

  #在实现了 implements WebMvcConfigurer接口时，此配置是无效的
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
---
spring.profiles: dev
spring.profiles.include: dao-dev

sms:
  ali:
    key-string: key-string
    secret: secret
  enable: true

# 指定log4j2作为日志记录
logging:
  config: classpath:logback-spring.xml
#  config: classpath:logback-logstash.xml
#  config: classpath:log4j2-dev.xml
#  config: classpath:log4j2-8090.xml
#  config: classpath:log4j2-8091.xml

jwt:
  secret: jwt:secret

test:
#  list:
#    - cc
#    - dd

#  list: aaa,bbb,vvv
  map: '{"id": 12, "name": "zhangsan", "sex": "male"}'